### ISSUE TITLE
404s when I try to access the PPT files

### ISSUE THREAD

**Issue by rrdkent** [MIDS-INFO-W18/Installation#1]
Under the "First excercise with Git" section, when I try to access the "1.15 The Course Workflow.pptx" and "https://github.com/MIDS-INFO-W18/assignment-upstream-summer17" files via the links in the Completing Your First Exercise With Git Reading Card.md, I get a 404 file not found error.  Halp?

**Comment by yuchenzhang10** [comment]
i too get this

**Comment by christopher-llop** [comment]
The issue occured because we keep the course materials in a separate
repository.  I've now made sure everyone has access.

You can see the file you referenced here:
https://github.com/MIDS-INFO-W18/Course-Syllabus/tree/master/week_01
