### ISSUE TITLE
404s when I try to access the PPT files

### ISSUE THREAD

**Issue by CraigFujii-ischool** [MIDS-INFO-W18/Installation#4]
Unable to download 1.15 The Course Workflow.pptx:
Download [1.15 The Course Workflow.pptx](https://github.com/MIDS-INFO-W18/Course-Syllabus/blob/master/week_01/1.15%20The%20Course%20Workflow.pptx) for a diagram of this process

It looks like same situation as before: https://github.com/MIDS-INFO-W18/Installation/issues/1

Thanks,
Craig

**Comment by gunnarklee** [comment]
Thanks for the heads up. The students Fall 2017 team  should have access
now.

**Comment by rodeosaint** [comment]
I too have the same warning, even now.

**Comment by pkurapati** [comment]
Same here. Unable to download

**Comment by CraigFujii-ischool** [comment]
I was able to access. Be sure to click on Download. Thanks
